# Runs code quality check on all the files in the repo

name: Code Quality Check

on:
  pull_request:
  push:
    branches:
      - main
      - release/therock-*

permissions:
  contents: read

jobs:
  code-quality:
    runs-on: aws-linux-scale-rocm-small
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
         persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'
      # Runs pre-commit with the argument --all-files
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Add help message on failure
        if: failure()
        run: |
          echo "## Pre-commit checks failed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Some files need formatting or have linting errors." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "See [Formatting using pre-commit hooks](https://github.com/${{ github.repository }}/blob/main/README.md#formatting-using-pre-commit-hooks) for instructions on running the style checker locally." >> $GITHUB_STEP_SUMMARY
