name: Runfile Installer CI

on:
  push:
    branches:
      - main
      - release/therock-*
  pull_request:
    branches:
      - main
      - release/therock-*

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Get latest ROCm and AMDGPU Driver Version
    runs-on: ubuntu-24.04
    outputs:
      rocm_version: ${{ steps.params.outputs.rocm_version }}  # Set by script setup_runfile_installer_ci.py
      pull_amdgpu: ${{ steps.params.outputs.pull_amdgpu }}

    steps:
     - name: Checkout repository
       uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
       with:
         persist-credentials: false

     - name: Setup Python
       uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
       with:
         python-version: 3.12

     - name: Setup parameters
       id: params
       run: python ./runfile-installer/build_tools/github_actions/setup_runfile_installer_ci.py

  runfile_installer_ci:
    name: Basic Runfile Installer Build
    needs: setup
    permissions:
      contents: read
    uses: ./.github/workflows/build_linux_runfile_installer.yaml
    with:
      rocm_version: ${{ needs.setup.outputs.rocm_version }}
      release_type: dev
      pull_type: stable
      pull_pkg: amdrocm-core-sdk
      gfx_archs: gfx1100
      pull_amdgpu: ${{ needs.setup.outputs.pull_amdgpu }}
      upload_to_s3: false
