name: Style checker

on:
  pull_request:
  push:
    branches: 
      - main
      - release/therock-*

permissions:
  contents: read

jobs:
  style-checker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2 # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a309ff8 # v6.2.0
      - uses: pre-commit/action@2c7b380 # v3.0.1